version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: 'dreamyTrip'
    env_file: ./container/containerConfig/mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ./container/containerConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./container/data/mongdb:/data/db
    command: mongod --logpath=/dev/null # --quiet
