version: '3.1'
services:
  dbTest:
    image: mongo:latest
    restart: always
    container_name: 'dbTest'
    env_file: ./containers/dbConfig/dbTest.env
    ports:
      - 27018:27018
    volumes:
      - ./containers/dbConfig/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
      - ./containers/data/dbConfig/mongdb:/data/dbTest
    command: mongod --port 27018 --logpath=/dev/null
